---
- name: Test inventory sources vars merging
  hosts: localhost
  tasks:

    - debug:
        var: sn_username

    - debug:
        var: sn_password

    - name: Create incident
      servicenow.itsm.incident:
        instance:
          host: https://dev109340.service-now.com
          username: "{{ sn_username }}"
          password: "{{ sn_password }}"
    
        state: new
        caller: admin
        short_description: Missing vars for host
        description: Missing vars
        impact: low
        urgency: low
